name: Deploy to GitHub Pages

on:
  push:
    branches: ['main'] # o 'master' si esa es tu rama principal

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        # Aquí es donde le pasamos los secretos ocultos de GitHub a tu código al momento de compilar
        env:
          VITE_DRIVE_API_KEY: ${{ secrets.VITE_DRIVE_API_KEY }}
          VITE_DRIVE_FOLDER_SEMIPERMANENTE: ${{ secrets.VITE_DRIVE_FOLDER_SEMIPERMANENTE }}
          VITE_DRIVE_FOLDER_PRESS_ON: ${{ secrets.VITE_DRIVE_FOLDER_PRESS_ON }}
          VITE_DRIVE_FOLDER_POLYGEL: ${{ secrets.VITE_DRIVE_FOLDER_POLYGEL }}
          VITE_DRIVE_FOLDER_TRADICIONAL: ${{ secrets.VITE_DRIVE_FOLDER_TRADICIONAL }}
        run: npm run build
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
